### PR TITLE
File uploader for json 

### PR DESCRIPTION
**Pull request by Vinit-Pandit**
ref #4 
[Screencast from 17-04-24 10:36:07 AM IST.webm](https://github.com/sourcemeta/json-taxonomy/assets/106718914/929c8127-32c2-4d8d-8fd5-0c6fe3db6d67)

The file contains 75,000 lines of code, which is why it takes the FileReader a significant amount of time to read it.

### CODE REVIEW

**Comment by Vinit-Pandit** [comment]
@jviotti please review this PR

**Comment by jviotti** [comment]
Is looking good! The only comments I have is around the UI being slightly confusing with the code editor + the upload file. What about this?

- If the user has uploaded a file, then completely gray out (saying something like "Reading the uploaded input file") or even remove the inline code editor
- If you click "Remove file", the editor comes back?

**Comment by Vinit-Pandit** [comment]
> Is looking good! The only comments I have is around the UI being slightly confusing with the code editor + the upload file. What about this?
> 
> * If the user has uploaded a file, then completely gray out (saying something like "Reading the uploaded input file") or even remove the inline code editor
> * If you click "Remove file", the editor comes back?

The editor isn't being removed, but the code in the editor removed. The editor remains, but when a file is uploaded, the file takes priority until it is removed.

**Comment by Vinit-Pandit** [comment]
> Is looking good! The only comments I have is around the UI being slightly confusing with the code editor + the upload file. What about this?
> 
> * If the user has uploaded a file, then completely gray out (saying something like "Reading the uploaded input file") or even remove the inline code editor
> * If you click "Remove file", the editor comes back?


Yes, that's a good idea. I'll implement it in a few weeks, as I currently have academic exams. : )

**Comment by Vinit-Pandit** [comment]
[Screencast from 24-04-24 02:02:47 AM IST.webm](https://github.com/sourcemeta/json-taxonomy/assets/106718914/2f295bcf-38f6-421e-a5e9-3033c07a2477)

**Comment by jviotti** [comment]
Looks better based on the video! I'll give it a proper shot and review tomorrow

**Comment by jviotti** [comment]
Looks and feels much better. The two comments I have are:

- When you select a file, can you just put a read-only message where the editor was saying "Reading from input file" or something like that? 
- When there is no file selected, can you either hide or make the "Remove File" button disabled, as it wouldn't do anything in those cases?

**Comment by Vinit-Pandit** [comment]
> * When you select a file, can you just put a read-only message where the editor was saying "Reading from input file" or something like that?

If i do that the default schema which was previously in editor get remove if i am not wrong , is this Ok ? or else i need to store the previous schema in temp variable .

**Comment by jviotti** [comment]
Yeah, if you have a schema in the editor and you upload a file, removing what you had on the editor makes sense. No need to keep it around

**Comment by Vinit-Pandit** [comment]
@jviotti 
[Screencast from 27-04-24 07:15:35 PM IST.webm](https://github.com/sourcemeta/json-taxonomy/assets/106718914/bc5f7f50-a3ed-4b24-9287-e61f7d007564)

**Review by jviotti — APPROVED** [review]
Looks good!

**Pull request merged**
